name: Test
run-name: Sraping Jobs 🚀
on:
  push:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  ScrapeJobs:
    runs-on: ubuntu-latest
    permissions: write-all
    outputs:
      SCRAPER_OUTPUTS: ${{ steps.runScraper.outputs.SCRAPER_OUTPUTS }}
    steps:
      - run: echo "🎉 The job was automatically triggered by a event."

      - name: checkout repo
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: install requirements
        run: pip install -r requirements.txt

      - id: runScraper
        run: python scrape.py

      - name: Commit changes
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add --all
          if [ -z "$(git status --porcelain)" ]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Updating readmes" -a
            echo "::set-output name=push::true"
          fi
        shell: bash
      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

  create-issue:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    needs: ScrapeJobs
    steps:
      - env:
          SCRAPER_OUTPUTS: ${{needs.ScrapeJobs.outputs.SCRAPER_OUTPUTS}}
        run: echo "$SCRAPER_OUTPUTS"

      - name: Get Current Time as ENV
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV

      - env:
          SCRAPER_OUTPUTS: ${{needs.ScrapeJobs.outputs.SCRAPER_OUTPUTS}}
        name: Create Issue With Results
        uses: dacbd/create-issue-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: New Jobs Scraped - ${{ env.NOW }}
          labels: scrape
          body: ${{env.SCRAPER_OUTPUTS}}
  
  send-email:
    needs: [ScrapeJobs, create-issue]
    runs-on: ubuntu-latest
    steps:
      - name: Send email with job changes
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Job Scraper Results"
          to: testingalcove@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          body: ${{ needs.ScrapeJobs.outputs.SCRAPER_OUTPUTS }}
